import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import Provider from "./Provider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CoDraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
      variables: { colorPrimary: "#3371FF"},
    }}
    >
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <script src="./node_modules/preline/dist/preline.js" async></script>
       <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
